Update code

diff --git a/.github/workflows/build-feature.yaml b/.github/workflows/build-feature.yaml
--- a/.github/workflows/build-feature.yaml
+++ b/.github/workflows/build-feature.yaml
@@ -13,15 +13,17 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
       
-      # Set up Java
-      - name: Set up Java
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'zulu'
-          java-version: '17'
+      # Ensure Maven wrapper exists
+      - name: Ensure Maven wrapper exists
+        run: |
+          if [ ! -f ./customer-back/mvnw ]; then
+            echo "Maven wrapper not found!"
+            exit 1
+          fi
       
       # Grant execute permissions to Maven wrapper
       - name: Grant execute permissions to Maven wrapper
+        working-directory: ./customer-back
         run: chmod +x mvnw
       
       # Build with Maven
